import { User, Role, Patient, Language, RestType, Permission } from './types';

export const USERS: User[] = [
    { id: 1, name: 'Dr. Ahmad', role: Role.Doctor, password: 'password123', permissions: [Permission.GiveSickLeave, Permission.DoReferral, Permission.AdministerVaccine, Permission.PerformProcedures] },
    { id: 2, name: 'Nurse Fatima', role: Role.Nurse, password: 'password123', permissions: [Permission.AdministerVaccine, Permission.PerformProcedures] },
    { id: 3, name: 'Reem (Reception)', role: Role.Reception, password: 'password123', permissions: [] },
    { id: 4, name: 'Mr. Hassan (Manager)', role: Role.Manager, password: 'password123', permissions: [] },
    { id: 5, name: 'Ali (Pharmacy)', role: Role.Pharmacist, password: 'password123', permissions: [] },
    { id: 6, name: 'Dr. Sara (ER)', role: Role.ER_Specialist, password: 'password123', permissions: [Permission.GiveSickLeave, Permission.DoReferral, Permission.PerformProcedures]},
    { id: 7, name: 'Sami (Technician)', role: Role.Technician, password: 'password123', permissions: [Permission.PerformProcedures]},
    { id: 8, name: 'Dr. Omar (Dentist)', role: Role.Dentist, password: 'password123', permissions: [Permission.GiveSickLeave, Permission.DoReferral, Permission.PerformProcedures]},
    { id: 9, name: 'Layla (Lab)', role: Role.Lab, password: 'password123', permissions: [Permission.PerformProcedures] },
    { id: 10, name: 'Fahad (Radiology)', role: Role.Radiology, password: 'password123', permissions: [Permission.PerformProcedures] }
];

export const MOCK_PATIENTS: Patient[] = [
    {
        id: 'P001',
        name: 'Khalid Al-Fahad',
        age: 34,
        idNumber: '1098765432',
        phone: '0501234567',
        registrationDate: '2023-10-01',
        allergies: ['Penicillin'],
        pretendedSickCount: 0,
        visits: [
            {
                id: 'V001-1',
                date: '2023-10-26',
                status: 'completed',
                consentSigned: true,
                vitals: {
                    date: '2023-10-26',
                    height: 175,
                    weight: 80,
                    temperature: 37.2,
                    bloodPressure: '120/80',
                    heartRate: 75,
                    respiratoryRate: 16,
                    recordedBy: 'Nurse Fatima',
                },
                diagnosis: 'Common Cold',
                procedures: [{ name: 'IV Saline Drip', performedById: 2, performedDate: '2023-10-26T14:00:00Z' }],
                prescription: {
                    items: [
                        { medication: 'Panadol Cold & Flu', dosage: '2 tablets', frequency: '3 times a day', duration: '5 days'},
                        { medication: 'Amoxicillin', dosage: '500mg', frequency: '2 times a day', duration: '7 days'}
                    ],
                    issuedBy: 'Dr. Ahmad',
                    date: '2023-10-26',
                    isDispensed: true,
                    dispensedById: 5,
                    dispensedDate: '2023-10-26T14:30:00Z'
                },
                soapNotes: {
                    subjective: ['Cough', 'Runny nose'],
                    objective: ['Mild fever', 'Red throat'],
                    assessment: ['Viral upper respiratory infection.'],
                    plan: ['Advised rest', 'Increase fluid intake'],
                    notes: 'Patient complains of symptoms for 3 days. Re-evaluate in 3-5 days if no improvement.'
                },
                vaccines: [{ name: 'Influenza Shot', dose: '2023 annual' }],
                seenBy: { nurseId: 2, doctorId: 1 }
            }
        ]
    },
    {
        id: 'P002',
        name: 'Sara Abdullah',
        age: 28,
        idNumber: '2012345678',
        phone: '0558765432',
        registrationDate: '2023-11-05',
        allergies: [],
        pretendedSickCount: 1, // This patient has a history
        visits: [
            {
                id: 'V002-1',
                date: '2023-11-10',
                status: 'completed',
                consentSigned: true,
                vitals: {
                    date: '2023-11-10',
                    height: 162,
                    weight: 55,
                    temperature: 38.5,
                    bloodPressure: '110/70',
                    heartRate: 90,
                    respiratoryRate: 20,
                    recordedBy: 'Nurse Fatima',
                },
                diagnosis: 'Influenza',
                sickLeave: {
                    days: 3,
                    reason: 'Influenza',
                    restType: RestType.BedRest,
                    issuedBy: 'Dr. Ahmad',
                    date: '2023-11-10'
                },
                referral: {
                    to: 'King Fahad Specialist Hospital',
                    reason: 'Further cardiac evaluation',
                    issuedBy: 'Dr. Ahmad',
                    date: '2023-11-10',
                    patientId: 'P002'
                },
                isPretending: true, // Marked in this visit
                soapNotes: {
                    subjective: ['High fever', 'Muscle aches', 'Fatigue'],
                    objective: ['Temperature 38.5°C.', 'Appears lethargic.'],
                    assessment: ['Influenza.'],
                    plan: ['Prescribed antiviral medication.', 'Advised bed rest and hydration.'],
                    notes: 'Issued sick leave for 3 days. Patient seemed to be exaggerating symptoms.'
                },
                seenBy: { nurseId: 2, doctorId: 1 }
            }
        ]
    }
];

// Default data for settings context
export const INITIAL_DIAGNOSES = ['Common Cold', 'Influenza', 'Allergic Rhinitis', 'Gastroenteritis', 'Migraine', 'Hypertension'];
export const INITIAL_MEDICATIONS = ['Panadol', 'Amoxicillin', 'Loratadine', 'Omeprazole', 'Ibuprofen', 'Metformin', 'Panadol Cold & Flu'];
export const INITIAL_ALLERGIES = ['Penicillin', 'Sulfa drugs', 'Aspirin', 'Nuts', 'Shellfish', 'Pollen'];
export const INITIAL_VACCINES = ['BCG', 'Hepatitis B', 'Polio', 'MMR', 'Influenza Shot', 'COVID-19 Vaccine'];
export const INITIAL_PROCEDURES = ['Oxygen Supply', 'IV Injection', 'Suturing', 'Wound Dressing', 'IV Saline Drip'];
export const INITIAL_SOAP_SUBJECTIVE = ['Headache', 'Fever', 'Cough', 'Sore throat', 'Nausea', 'Vomiting', 'Dizziness', 'Runny nose', 'High fever', 'Muscle aches', 'Fatigue'];
export const INITIAL_SOAP_OBJECTIVE = ['Temperature: 38.5°C', 'BP: 120/80 mmHg', 'HR: 80 bpm', 'Red throat', 'Lungs clear', 'Mild fever', 'Appears lethargic.'];
export const INITIAL_SOAP_ASSESSMENT = ['Common Cold', 'Influenza', 'Gastroenteritis', 'Migraine', 'Viral upper respiratory infection.'];
export const INITIAL_SOAP_PLAN = ['Advised rest', 'Increase fluid intake', 'Prescribed medication', 'Follow up in 3 days', 'Advised bed rest and hydration.'];
export const INITIAL_DENTAL_DIAGNOSES = ['Caries', 'Gingivitis', 'Periodontitis', 'Abscess', 'Wisdom Tooth Pain'];
export const INITIAL_LAB_TESTS = ['CBC', 'Lipid Profile', 'HbA1c', 'LFT', 'KFT', 'Urine Analysis'];
export const INITIAL_RADIOLOGY_ORDERS = ['Chest X-Ray', 'Dental X-Ray', 'Abdominal X-Ray', 'Limb X-Ray'];


type Translations = {
    [key in Language]: { [key: string]: string }
}

export const translations: Translations = {
    en: {
        appName: "Public Security Training City Health Center - Qassim",
        dashboard: "Dashboard",
        patients: "Patients",
        users: "User Management",
        settings: "Settings",
        logout: "Logout",
        welcome: "Welcome",
        statistics: "Clinic Statistics",
        commonDiagnoses: "Common Diagnoses",
        commonPrescriptions: "Common Prescriptions",
        patientList: "Patient List",
        searchPatients: "Search patients by name or ID...",
        newPatient: "New Patient",
        name: "Name",
        age: "Age",
        idNumber: "ID Number",
        phone: "Phone Number",
        actions: "Actions",
        view: "View",
        patientFile: "Patient File",
        backToList: "Back to List",
        patientInfo: "Patient Information",
        registrationDate: "Registration Date",
        allergies: "Allergies",
        noAllergies: "No known allergies.",
        visitHistory: "Visit History",
        newVisit: "Start New Visit",
        vitals: "Vitals",
        height: "Height (cm)",
        weight: "Weight (kg)",
        temperature: "Temp (°C)",
        bp: "Blood Pressure",
        hr: "Heart Rate (bpm)",
        rr: "Resp. Rate",
        saveVitals: "Save Vitals",
        doctorSection: "Doctor's Section",
        diagnosis: "Diagnosis",
        selectDiagnosis: "Select a diagnosis",
        prescription: "Prescription",
        medication: "Medication",
        sickLeave: "Sick Leave",
        days: "Days",
        reason: "Reason",
        restType: "Type of Rest",
        referral: "Referral",
        referTo: "Refer to",
        pretendingToBeSick: "Patient pretends to be sick",
        saveConsultation: "Save & Complete Consultation",
        login: "Login",
        username: "Username",
        password: "Password",
        loginError: "Invalid username or password.",
        viewDetails: "View Details",
        hideDetails: "Hide Details",
        doctorNotes: "Doctor's Notes",
        consultationDetails: "Consultation Details",
        recordedBy: "Recorded by",
        prescribedBy: "Prescribed by",
        issuedBy: "Issued by",
        noVitals: "No vitals recorded for this visit.",
        noConsultation: "No consultation recorded for this visit.",
        dosage: "Dosage",
        frequency: "Frequency",
        duration: "Duration",
        permissions: "Permissions",
        canGiveSickLeave: "Can Give Sick Leave",
        canDoReferral: "Can Make Referrals",
        canAdministerVaccine: "Can Administer Vaccines",
        canPerformProcedures: "Can Perform Procedures",
        editUser: "Edit User",
        addUser: "Add User",
        save: "Save",
        cancel: "Cancel",
        role: "Role",
        vaccines: "Vaccines",
        vaccineName: "Vaccine Name",
        dose: "Dose / Details",
        addVaccine: "Add Vaccine",
        filterBy: "Filter by",
        day: "Day",
        week: "Week",
        month: "Month",
        year: "Year",
        allTime: "All Time",
        printReport: "Print Report",
        patientsPerDay: "Patients Per Day",
        sickLeavesIssued: "Sick Leaves Issued",
        commonVaccines: "Common Vaccines",
        allergyAlert: "ALLERGY ALERT!",
        patientHasAllergies: "This patient has known allergies to:",
        print: "Print",
        close: "Close",
        medicalProcedures: "Medical Procedures",
        procedure: "Procedure",
        addProcedure: "Add Procedure",
        manageClinicData: "Manage Clinic Data",
        manageExplanation: "Add or remove items from the lists used across the application.",
        addNew: "Add New",
        remove: "Remove",
        procedures: "Procedures",
        erSpecialist: "ER Specialist",
        auditLog: "Audit Log",
        notifications: "Notifications",
        noNewNotifications: "No new notifications.",
        markAsRead: "Mark as read",
        checkIn: "Check-in",
        patientConsent: "Patient Consent",
        consentConfirmation: "Has the patient signed the consent form for this visit?",
        confirm: "Confirm",
        subjective: "Subjective",
        objective: "Objective",
        assessment: "Assessment",
        plan: "Plan",
        soapNotes: "SOAP Notes",
        consentSigned: "Consent Signed",
        consentNotSigned: "Consent Not Signed",
        newPatientWaiting: "New patient waiting for vitals:",
        prescriptionReady: "Prescription ready for dispensing for:",
        proceduresReady: "Procedures assigned for patient:",
        sickLeaveReady: "Sick leave ready for printing for:",
        referralReady: "Referral ready for printing for:",
        user: "User",
        timestamp: "Timestamp",
        action: "Action",
        details: "Details",
        searchLogs: "Search logs by user or action...",
        notes: "Notes",
        BedRest: "Bed Rest",
        NoShoes: "No Heavy Shoes",
        NoWorkout: "No Workout",
        GeneralRest: "Rest",
        subjectiveChoices: "Subjective Choices",
        objectiveChoices: "Objective Choices",
        assessmentChoices: "Assessment Choices",
        planChoices: "Plan Choices",
        nursingSection: "Nursing & Vitals",
        saveAllergies: "Save Allergies",
        allergiesUpdated: "Allergies updated successfully!",
        saveNursingData: "Save Nursing Data",
        noActiveVisit: "This patient has no active visit. Please check-in from the patient list.",
        createNewPatient: "Create New Patient",
        enterPatientDetails: "Please enter the new patient's details.",
        allergiesPlaceholder: "Enter allergies, separated by commas",
        activeVisit: "Active Visit",
        prescriptionDetails: "Prescription Details",
        addMedication: "Add Medication",
        prescribedMedications: "Prescribed Medications",
        markAsDispensed: "Mark as Dispensed",
        dispensedBy: "Dispensed by",
        on: "on",
        technician: "Technician",
        proceduresPerformed: "Procedures Performed",
        behavioralNote: "BEHAVIORAL NOTE",
        pretendedSickHistory: "This patient has a history of feigning illness.",
        wasMarkedAsPretending: "Patient was marked as pretending to be sick for this visit.",
        notificationSent: "Notification Sent",
        noDataAvailable: "No data available for the selected period.",
        information: "Information",
        markAsPerformed: "Mark as Performed",
        performedBy: "Performed by",
        commonReferrals: "Common Referral Reasons",
        referralReason: "Referral Reason",
        showReports: "Show Reports",
        copyToClipboard: "Copy to Clipboard",
        copiedSuccess: "Statistics copied to clipboard!",
        dentist: "Dentist",
        lab: "Lab",
        radiology: "Radiology",
        dentalReferral: "Refer to Dentist",
        dentalReferralNotification: "Dental referral requested for:",
        dentistSection: "Dentist's Section",
        dentalDiagnosis: "Dental Diagnosis",
        selectDentalDiagnosis: "Select a dental diagnosis",
        dentalNotes: "Dental Notes",
        saveDentalConsultation: "Save & Complete Dental Consultation",
        dentalDiagnoses: "Dental Diagnoses",
        labOrders: "Laboratory Orders",
        radiologyOrders: "Radiology Orders",
        labTests: "Lab Tests",
        uploadImage: "Upload Image",
        viewImage: "View Image",
        uploadResult: "Upload Result",
        viewResult: "View Result",
        labTestReady: "New lab test ordered for:",
        radiologyOrderReady: "New radiology order for:",
        imageUploadWarning: "Image Upload & Data Storage Warning",
        imageUploadWarningBody: "The image upload feature stores images directly in your browser's local storage. This is convenient but has a strict size limit (usually 5-10MB total for the entire application). Uploading many high-resolution images can quickly fill this storage and cause the application to fail. For production use, a dedicated file server is recommended.",
        markAsPrinted: "Mark as Printed",
        printedBy: "Printed by",
        lanSetupTitle: "LAN Network Setup Guide",
        lanSetupBody1: "This application runs on a powerful client-server model, perfect for multi-user network environments. One computer acts as the 'server' (holding the central database), and all other computers ('clients') connect to it.",
        lanSetupStep1: "Step 1: Start the Server",
        lanSetupStep1Desc: "On your main computer (the 'server'), find the application's installation folder and run the `start_server.bat` (or equivalent) script. This will launch the central database and server. A terminal window will appear; this window must remain open for the application to function.",
        lanSetupStep2: "Step 2: Launch the Application",
        lanSetupStep2Desc: "After starting the server, launch the PrimeCare EMR application on the server computer. On all other client computers, simply launch the installed PrimeCare EMR application. It will automatically connect to the server computer over the network.",
        lanSetupImportantNote: "Important Note",
        lanSetupNoteDesc: "The server computer must always be running for the client computers to connect and function.",
        appUpdateTitle: "Application Updates",
        appUpdateBody: "To update the application, you will receive a new installer file. First, close the application on all computers and stop the server. Then, run the new installer on the server and on all client computers. Your data (`clinic.db` file) will be preserved.",
        dataBackupTitle: "Data Backup & Portability",
        dataBackupBody1: "All application data (patients, visits, users, settings) is stored in a single database file named `clinic.db`. This file is located in the same folder where you run the application server.",
        dataBackupBackupTitle: "How to Backup Data",
        dataBackupStep1: "Simply copy the `clinic.db` file to a secure location (like a USB drive or cloud storage). This single file is a complete backup of your entire clinic's data.",
        dataBackupRestoreTitle: "How to Restore Data",
        dataBackupRestoreWarning: "Warning: Restoring data will overwrite all current data in the application. Only do this if you are sure. Make a backup of the current file before restoring.",
        dataBackupRestoreStep1: "To restore from a backup, simply replace the current `clinic.db` file with your backup file. (Make sure the application server is stopped before you do this).",
    },
    ar: {
        appName: "المركز الصحي بمدينة تدريب الأمن العام بمنطقة القصيم",
        dashboard: "لوحة التحكم",
        patients: "المرضى",
        users: "إدارة المستخدمين",
        settings: "الإعدادات",
        logout: "تسجيل الخروج",
        welcome: "أهلاً بك",
        statistics: "إحصائيات العيادة",
        commonDiagnoses: "التشخيصات الشائعة",
        commonPrescriptions: "الوصفات الطبية الشائعة",
        patientList: "قائمة المرضى",
        searchPatients: "ابحث عن مريض بالاسم أو رقم الهوية...",
        newPatient: "مريض جديد",
        name: "الاسم",
        age: "العمر",
        idNumber: "رقم الهوية",
        phone: "رقم الجوال",
        actions: "الإجراءات",
        view: "عرض",
        patientFile: "ملف المريض",
        backToList: "العودة للقائمة",
        patientInfo: "معلومات المريض",
        registrationDate: "تاريخ التسجيل",
        allergies: "الحساسية",
        noAllergies: "لا توجد حساسية معروفة.",
        visitHistory: "سجل الزيارات",
        newVisit: "بدء زيارة جديدة",
        vitals: "العلامات الحيوية",
        height: "الطول (سم)",
        weight: "الوزن (كجم)",
        temperature: "الحرارة (°م)",
        bp: "ضغط الدم",
        hr: "نبض القلب",
        rr: "معدل التنفس",
        saveVitals: "حفظ العلامات",
        doctorSection: "قسم الطبيب",
        diagnosis: "التشخيص",
        selectDiagnosis: "اختر تشخيص",
        prescription: "وصفة طبية",
        medication: "الدواء",
        sickLeave: "إجازة مرضية",
        days: "أيام",
        reason: "السبب",
        restType: "نوع الراحة",
        referral: "تحويل",
        referTo: "تحويل إلى",
        pretendingToBeSick: "المريض يدعي المرض",
        saveConsultation: "حفظ وإنهاء المعاينة",
        login: "تسجيل الدخول",
        username: "اسم المستخدم",
        password: "كلمة المرور",
        loginError: "اسم المستخدم أو كلمة المرور غير صحيحة.",
        viewDetails: "عرض التفاصيل",
        hideDetails: "إخفاء التفاصيل",
        doctorNotes: "ملاحظات الطبيب",
        consultationDetails: "تفاصيل المعاينة",
        recordedBy: "سجل بواسطة",
        prescribedBy: "وصف بواسطة",
        issuedBy: "صدر بواسطة",
        noVitals: "لم تسجل علامات حيوية لهذه الزيارة.",
        noConsultation: "لم تسجل معاينة لهذه الزيارة.",
        dosage: "الجرعة",
        frequency: "التكرار",
        duration: "المدة",
        permissions: "الصلاحيات",
        canGiveSickLeave: "يمكنه إعطاء إجازة مرضية",
        canDoReferral: "يمكنه عمل تحويلات",
        canAdministerVaccine: "يمكنه إعطاء اللقاحات",
        canPerformProcedures: "يمكنه تنفيذ إجراءات طبية",
        editUser: "تعديل المستخدم",
        addUser: "إضافة مستخدم",
        save: "حفظ",
        cancel: "إلغاء",
        role: "الدور",
        vaccines: "اللقاحات",
        vaccineName: "اسم اللقاح",
        dose: "الجرعة / تفاصيل",
        addVaccine: "إضافة لقاح",
        filterBy: "تصفية حسب",
        day: "يوم",
        week: "أسبوع",
        month: "شهر",
        year: "سنة",
        allTime: "كل الوقت",
        printReport: "طباعة التقرير",
        patientsPerDay: "المرضى يومياً",
        sickLeavesIssued: "الإجازات المرضية المصدرة",
        commonVaccines: "اللقاحات الشائعة",
        allergyAlert: "تنبيه حساسية!",
        patientHasAllergies: "هذا المريض لديه حساسية معروفة من:",
        print: "طباعة",
        close: "إغلاق",
        medicalProcedures: "الإجراءات الطبية",
        procedure: "الإجراء",
        addProcedure: "إضافة إجراء",
        manageClinicData: "إدارة بيانات العيادة",
        manageExplanation: "إضافة أو إزالة عناصر من القوائم المستخدمة في التطبيق.",
        addNew: "إضافة جديد",
        remove: "إزالة",
        procedures: "الإجراءات",
        erSpecialist: "أخصائي طوارئ",
        auditLog: "سجل التدقيق",
        notifications: "الإشعارات",
        noNewNotifications: "لا توجد إشعارات جديدة.",
        markAsRead: "وضع علامة كمقروء",
        checkIn: "تسجيل وصول",
        patientConsent: "موافقة المريض",
        consentConfirmation: "هل وقع المريض على نموذج الموافقة لهذه الزيارة؟",
        confirm: "تأكيد",
        subjective: "الشكوى (Subjective)",
        objective: "الفحص (Objective)",
        assessment: "التقييم (Assessment)",
        plan: "الخطة (Plan)",
        soapNotes: "ملاحظات SOAP",
        consentSigned: "تم توقيع الموافقة",
        consentNotSigned: "لم يتم توقيع الموافقة",
        newPatientWaiting: "مريض جديد ينتظر العلامات الحيوية:",
        prescriptionReady: "وصفة طبية جاهزة للصرف للمريض:",
        proceduresReady: "تم تحديد إجراءات للمريض:",
        sickLeaveReady: "إجازة مرضية جاهزة للطباعة للمريض:",
        referralReady: "تحويل جاهز للطباعة للمريض:",
        user: "المستخدم",
        timestamp: "الوقت",
        action: "الإجراء",
        details: "التفاصيل",
        searchLogs: "ابحث في السجلات حسب المستخدم أو الإجراء...",
        notes: "ملاحظات",
        BedRest: "راحة سريرة",
        NoShoes: "راحة من البسطار",
        NoWorkout: "راحة من التمارين",
        GeneralRest: "راحة",
        subjectiveChoices: "خيارات الشكوى",
        objectiveChoices: "خيارات الفحص",
        assessmentChoices: "خيارات التقيييم",
        planChoices: "خيارات الخطة",
        nursingSection: "التمريض والعلامات الحيوية",
        saveAllergies: "حفظ الحساسية",
        allergiesUpdated: "تم تحديث الحساسية بنجاح!",
        saveNursingData: "حفظ بيانات التمريض",
        noActiveVisit: "لا توجد زيارة نشطة لهذا المريض. يرجى تسجيل الوصول من قائمة المرضى.",
        createNewPatient: "إنشاء ملف مريض جديد",
        enterPatientDetails: "الرجاء إدخال تفاصيل المريض الجديد.",
        allergiesPlaceholder: "أدخل الحساسية مفصولة بفواصل",
        activeVisit: "زيارة نشطة",
        prescriptionDetails: "تفاصيل الوصفة الطبية",
        addMedication: "إضافة دواء",
        prescribedMedications: "الأدوية الموصوفة",
        markAsDispensed: "تم الصرف",
        dispensedBy: "صرفت بواسطة",
        on: "في",
        technician: "فني",
        proceduresPerformed: "الإجراءات المنفذة",
        behavioralNote: "ملاحظة سلوكية",
        pretendedSickHistory: "هذا المريض لديه تاريخ في ادعاء المرض.",
        wasMarkedAsPretending: "تم تسجيل المريض على أنه يدعي المرض خلال هذه الزيارة.",
        notificationSent: "تم إرسال الإشعار",
        noDataAvailable: "لا توجد بيانات للفترة المحددة.",
        information: "معلومات",
        markAsPerformed: "تم التنفيذ",
        performedBy: "نفذت بواسطة",
        commonReferrals: "أسباب التحويل الشائعة",
        referralReason: "سبب التحويل",
        showReports: "عرض التقارير",
        copyToClipboard: "نسخ إلى الحافظة",
        copiedSuccess: "تم نسخ الإحصائيات إلى الحافظة!",
        dentist: "طبيب أسنان",
        lab: "مختبر",
        radiology: "أشعة",
        dentalReferral: "تحويل لعيادة الأسنان",
        dentalReferralNotification: "تم طلب تحويل لعيادة الأسنان للمريض:",
        dentistSection: "قسم طبيب الأسنان",
        dentalDiagnosis: "تشخيص الأسنان",
        selectDentalDiagnosis: "اختر تشخيص أسنان",
        dentalNotes: "ملاحظات طبيب الأسنان",
        saveDentalConsultation: "حفظ وإنهاء معاينة الأسنان",
        dentalDiagnoses: "تشخيصات الأسنان",
        labOrders: "طلبات المختبر",
        radiologyOrders: "طلبات الأشعة",
        labTests: "فحوصات مخبرية",
        uploadImage: "رفع صورة",
        viewImage: "عرض الصورة",
        uploadResult: "رفع النتيجة",
        viewResult: "عرض النتيجة",
        labTestReady: "طلب فحص مخبري جديد للمريض:",
        radiologyOrderReady: "طلب أشعة جديد للمريض:",
        imageUploadWarning: "تحذير رفع الصور وتخزين البيانات",
        imageUploadWarningBody: "ميزة تحميل الصور تخزن الصور مباشرة في التخزين المحلي للمتصفح. هذا مناسب ولكنه يحتوي على حد صارم للحجم (عادة 5-10 ميغابايت للتطبيق بأكمله). قد يؤدي تحميل العديد من الصور عالية الدقة إلى ملء هذه السعة التخزينية بسرعة والتسبب في فشل التطبيق. للاستخدام الفعلي، يوصى باستخدام خادم ملفات مخصص.",
        markAsPrinted: "تمت الطباعة",
        printedBy: "طبعت بواسطة",
        lanSetupTitle: "دليل إعداد شبكة LAN",
        lanSetupBody1: "يعمل هذا التطبيق على نموذج خادم-عميل قوي، وهو مثالي لبيئات الشبكات متعددة المستخدمين. يعمل جهاز كمبيوتر واحد 'كالخادم' (يحتوي على قاعدة البيانات المركزية)، وتتصل به جميع أجهزة الكمبيوتر الأخرى ('العملاء').",
        lanSetupStep1: "الخطوة 1: تشغيل الخادم",
        lanSetupStep1Desc: "على جهاز الكمبيوتر الرئيسي ('الخادم')، انتقل إلى مجلد تثبيت التطبيق وقم بتشغيل البرنامج النصي `start_server.bat` (أو ما يعادله). سيؤدي هذا إلى تشغيل قاعدة البيانات والخادم المركزي. ستظهر نافذة طرفية؛ يجب أن تظل هذه النافذة مفتوحة حتى يعمل التطبيق.",
        lanSetupStep2: "الخطوة 2: تشغيل التطبيق",
        lanSetupStep2Desc: "بعد بدء تشغيل الخادم، قم بتشغيل تطبيق PrimeCare EMR على جهاز الخادم. على جميع أجهزة الكمبيوتر العميلة الأخرى، ما عليك سوى تشغيل تطبيق PrimeCare EMR المثبت. سيتصل تلقائيًا بجهاز الخادم عبر الشبكة.",
        lanSetupImportantNote: "ملاحظة هامة",
        lanSetupNoteDesc: "يجب أن يكون جهاز الخادم قيد التشغيل دائمًا حتى تتمكن أجهزة الكمبيوتر العميلة من الاتصال والعمل.",
        appUpdateTitle: "تحديثات التطبيق",
        appUpdateBody: "لتحديث التطبيق، ستتلقى ملف تثبيت جديد. أولاً، أغلق التطبيق على جميع أجهزة الكمبيوتر وأوقف الخادم. بعد ذلك، قم بتشغيل المثبت الجديد على الخادم وعلى جميع أجهزة الكمبيوتر العميلة. سيتم الحفاظ على بياناتك (ملف `clinic.db`).",
        dataBackupTitle: "النسخ الاحتياطي للبيانات وقابليتها للنقل",
        dataBackupBody1: "يتم تخزين جميع بيانات التطبيق (المرضى، الزيارات، المستخدمون، الإعدادات) في ملف قاعدة بيانات واحد يسمى `clinic.db`. يوجد هذا الملف في نفس المجلد الذي تقوم بتشغيل خادم التطبيق منه.",
        dataBackupBackupTitle: "كيفية عمل نسخة احتياطية من البيانات",
        dataBackupStep1: "ما عليك سوى نسخ ملف `clinic.db` إلى مكان آمن (مثل محرك أقراص USB أو التخزين السحابي). هذا الملف الواحد هو نسخة احتياطية كاملة لبيانات عيادتك بأكملها.",
        dataBackupRestoreTitle: "كيفية استعادة البيانات",
        dataBackupRestoreWarning: "تحذير: ستؤدي استعادة البيانات إلى الكتابة فوق جميع البيانات الحالية في التطبيق. قم بذلك فقط إذا كنت متأكدًا. قم بعمل نسخة احتياطية من الملف الحالي قبل الاستعادة.",
        dataBackupRestoreStep1: "للاستعادة من نسخة احتياطية، ما عليك سوى استبدال ملف `clinic.db` الحالي بملف النسخ الاحتياطي الخاص بك. (تأكد من إيقاف خادم التطبيق قبل القيام بذلك).",
    }
};